### ISSUE TITLE
Windows Phone 7

### ISSUE THREAD

**Issue by chlastaldo** [danielbruce/entypo#7]
But i have problem in Windows Phone 7. Some icons are not rendered.

**Comment by puzrin** [comment]
Who cares about winmo7, that still can't support standards :) ?

Now seriously. Please, provide details, what exactly is not rendered. Screenshot or glyph codes. also try to replace direct codes with escaped sequenses in CSS (they are in comments). I have no winmo7 to play with.

**Comment by puzrin** [comment]
Closed since no feedback & nobody else confirmed.

**Comment by chlastaldo** [comment]
Sorry i have more work in job.
Here you are screenshot http://img262.imageshack.us/img262/6025/entypo.png

**Comment by puzrin** [comment]
Thanks for info. As far as i see, WP7 understands 6.1 unicode, but fails to load font files. Please, try this things:
1. Make font with http://fontello.com , because it includes some SVG fixes, that can matter in your case.
2. Please, move reports to fontello's tracker, because it's not specific to entypo. https://github.com/fontello/fontello/issues
3. If new font does not work too, please, try to find any working example with fontface (to make shure, that it warks at all in WP7), and give me link. I'll try to understand difference.
